/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
    id("gradle.plugin.greeting") version("0.1.0")
}

dependencies {
    api(project(":list"))
}
